Sonarqube integrated in Github Workflows

diff --git a/.github/workflows/AndroidBuild.yml b/.github/workflows/AndroidBuild.yml
--- a/.github/workflows/AndroidBuild.yml
+++ b/.github/workflows/AndroidBuild.yml
@@ -9,12 +9,12 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    services:
-      sonarqube:
-        image: sonarqube:community
-        ports:
-          - 9000:9000
-        options: --health-cmd="curl -f http://localhost:9000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
+#    services:
+#      sonarqube:
+#        image: sonarqube:community
+#        ports:
+#          - 9000:9000
+#        options: --health-cmd="curl -f http://localhost:9000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -35,14 +35,14 @@ jobs:
       - name: Create local.properties
         run: echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties
 
-      - name: Wait for SonarQube to be up
-        run: |
-            echo "Waiting for SonarQube to start..."
-            until $(curl --output /dev/null --silent --head --fail http://localhost:9000); do
-              printf '.'
-              sleep 5
-            done
-            echo "SonarQube is up and running"
+#      - name: Wait for SonarQube to be up
+#        run: |
+#            echo "Waiting for SonarQube to start..."
+#            until $(curl --output /dev/null --silent --head --fail http://localhost:9000); do
+#              printf '.'
+#              sleep 5
+#            done
+#            echo "SonarQube is up and running"
             
 #      - name: Run lint
 #        run: ./gradlew ktlintFormat lint detekt ktlintCheck
